'use client';
import {isVideoSource} from '@/lib/cms/media';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {blankProject,blankPhoto,type Photo,type CMSProject,type ProjectRecord} from '@/lib/cms/project-schema';

function Choice({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(value:string)=>void}){return <label className="cms-field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>}
function Lines({label,values,onChange}:{label:string;values:string[];onChange:(values:string[])=>void}){const [value,setValue]=useState(values.join('\n'));return <label className="cms-field"><span>{label} — un par ligne</span><Textarea value={value} onChange={e=>{setValue(e.target.value);onChange(e.target.value.split('\n').map(s=>s.trim()).filter(Boolean));}}/></label>}
export function PhotoField({label,photo,onChange,onUpload,allowVideo=false}:{allowVideo?:boolean;label:string;photo:Photo;onChange:(photo:Photo)=>void;onUpload:(delta:number)=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function upload(file:File){setBusy(true);onUpload(1);setError('');try{const form=new FormData();form.append('file',file);const response=await fetch('/api/admin/media',{method:'POST',body:form});const data=await response.json() as {error?:string;src:string};if(!response.ok)throw new Error(data.error);onChange({...photo,src:data.src,poster:undefined});}catch(error){setError(error instanceof Error?error.message:'Import impossible.');}finally{setBusy(false);onUpload(-1);}}
 return <div className="cms-photo"><h4>{label}</h4>{photo.src?isVideoSource(photo.src)?<video src={photo.src} poster={photo.poster} aria-label={photo.alt||label} controls muted loop playsInline preload="metadata" style={{objectFit:photo.fit,objectPosition:photo.position}}/>:<img src={photo.src} alt={photo.alt||label} style={{objectFit:photo.fit,objectPosition:photo.position}}/>:<div className="cms-photo-empty">Aucune image</div>}<label className="cms-field"><span>{busy?'Import en cours…':(allowVideo?'Importer une photo ou une vidéo':'Importer une photo')}</span><Input type="file" accept={"image/jpeg,image/png,image/webp,image/gif,image/avif"+(allowVideo?",video/mp4,video/webm":"")} disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label><label className="cms-field"><span>Texte alternatif</span><Input value={photo.alt} onChange={e=>onChange({...photo,alt:e.target.value})}/></label><Choice label="Cadrage" value={photo.fit} options={[["cover","Remplir"],["contain","Image entière"]]} onChange={v=>onChange({...photo,fit:v as Photo['fit']})}/><Choice label="Position" value={photo.position} options={[["center","Centre"],["top","Haut"],["bottom","Bas"],["left","Gauche"],["right","Droite"]]} onChange={v=>onChange({...photo,position:v as Photo['position']})}/>{photo.src&&<Button type="button" variant="outline" onClick={()=>onChange({...photo,src:''})}>Retirer le média</Button>}{error&&<p role="alert" className="cms-error">{error}</p>}</div>
}
function Editor({initial,onSaved,onDirty}:{initial:ProjectRecord;onSaved:(r:ProjectRecord)=>void;onDirty:(dirty:boolean)=>void}){
 const [p,setProject]=useState(initial.project),[revision,setRevision]=useState(initial.revision),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[uploads,setUploads]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('');
 const update=(next:CMSProject)=>{setProject(next);setMessage('');onDirty(true);};
 const field=(key:keyof CMSProject,value:unknown)=>update({...p,[key]:value});
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const response=await fetch('/api/admin/projects',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:p,revision})});const data=await response.json() as {error?:string;revision:number};if(!response.ok)throw new Error(data.error);setRevision(data.revision);setSaved(true);onDirty(false);onSaved({project:p,revision:data.revision});setMessage(p.published?'Projet enregistré et publié.':'Brouillon enregistré.');}catch(error){setError(error instanceof Error?error.message:'La sauvegarde a échoué.');}finally{setSaving(false);}}
 const uploadCounter=(delta:number)=>{setUploads(n=>n+delta);if(delta>0)onDirty(true);};
 const gallery=(key:keyof CMSProject['galleries'],photos:Photo[])=>field('galleries',{...p.galleries,[key]:photos});
 return <form onSubmit={save}><div className="cms-toolbar"><h2>{p.title||'Nouveau projet'}</h2><Button disabled={saving||uploads>0} type="submit">{saving?'Enregistrement…':'Enregistrer'}</Button></div><p role="status">{message|| (uploads>0?'Import des photos en cours…':'')}</p>{error&&<p role="alert" className="cms-error">{error}</p>}<fieldset disabled={saving||uploads>0} className="cms-fields"><section><h3>Informations du projet</h3><div className="cms-grid">{([['title','Nom du projet'],['id','Identifiant dans l’URL'],['category','Type de projet'],['sector','Secteur'],['year','Année']] as const).map(([key,label])=><label className="cms-field" key={key}><span>{label}</span><Input required={key==='title'||key==='id'} pattern={key==='id'?'[a-z0-9]+(-[a-z0-9]+)*':undefined} readOnly={key==='id'&&(!!initial.project.id||saved)} value={p[key]} onChange={e=>field(key,e.target.value)}/></label>)}<label className="cms-field"><span>Description sur les cartes</span><Textarea value={p.description} onChange={e=>field('description',e.target.value)}/></label><Lines label="Développement" values={p.development} onChange={v=>field('development',v)}/><Lines label="Services" values={p.services} onChange={v=>field('services',v)}/></div><div className="cms-options"><label><Checkbox checked={p.published} onCheckedChange={v=>field('published',v===true)}/>Publier l’étude de cas</label><label><Checkbox checked={p.listed} onCheckedChange={v=>field('listed',v===true)}/>Afficher la carte sur le site</label></div></section>
 <section><h3>Médias principaux</h3><p>La couverture alimente la carte projet. La photo d’ouverture apparaît en haut de l’étude de cas.</p><div className="cms-grid"><PhotoField allowVideo label="Couverture de la carte" photo={p.cover} onChange={v=>field('cover',v)} onUpload={uploadCounter}/><PhotoField allowVideo label="Photo d’ouverture" photo={p.hero} onChange={v=>field('hero',v)} onUpload={uploadCounter}/></div></section>
 {([['context','Le contexte'],['challenges','Les enjeux'],['decisions','Nos décisions'],['results','Les résultats']] as const).map(([key,title])=><section key={key}><h3>{title}</h3><label className="cms-field"><span>Texte</span><Textarea rows={6} value={p[key]} onChange={e=>field(key,e.target.value)}/></label>{key==='results'&&<div className="cms-metrics"><h4>Chiffres clés</h4>{p.metrics.map((metric,i)=><div className="cms-metric" key={i}><Input aria-label={'Valeur '+(i+1)} placeholder="+30" value={metric.value} onChange={e=>field('metrics',p.metrics.map((m,j)=>j===i?{...m,value:e.target.value}:m))}/><Input aria-label={'Libellé '+(i+1)} placeholder="Investisseurs" value={metric.label} onChange={e=>field('metrics',p.metrics.map((m,j)=>j===i?{...m,label:e.target.value}:m))}/><Button type="button" variant="outline" onClick={()=>field('metrics',p.metrics.filter((_,j)=>j!==i))}>Retirer</Button></div>)}<Button type="button" variant="outline" disabled={p.metrics.length>=12} onClick={()=>field('metrics',[...p.metrics,{value:'',label:''}])}>Ajouter un chiffre</Button></div>}<h4>Photos et vidéos après cette section</h4><div className="cms-grid">{p.galleries[key].map((photo,i)=><div key={i}><PhotoField allowVideo label={'Photo '+(i+1)} photo={photo} onChange={v=>gallery(key,p.galleries[key].map((x,j)=>j===i?v:x))} onUpload={uploadCounter}/><div className="cms-photo-actions"><Button type="button" variant="outline" disabled={i===0||uploads>0} onClick={()=>{const photos=[...p.galleries[key]];[photos[i-1],photos[i]]=[photos[i],photos[i-1]];gallery(key,photos);}}>Monter</Button><Button type="button" variant="outline" disabled={i===p.galleries[key].length-1||uploads>0} onClick={()=>{const photos=[...p.galleries[key]];[photos[i],photos[i+1]]=[photos[i+1],photos[i]];gallery(key,photos);}}>Descendre</Button><Button type="button" variant="outline" disabled={uploads>0} onClick={()=>gallery(key,p.galleries[key].filter((_,j)=>j!==i))}>Retirer</Button></div></div>)}</div><Button type="button" variant="outline" disabled={p.galleries[key].length>=30} onClick={()=>gallery(key,[...p.galleries[key],blankPhoto()])}>Ajouter un média</Button></section>)}
 </fieldset><div className="cms-toolbar"><Button disabled={saving||uploads>0} type="submit">Enregistrer</Button>{p.id&&(initial.project.id||saved)&&<a href={'/admin/projets/apercu?id='+p.id} target="_blank" rel="noreferrer">Voir la version enregistrée ↗</a>}</div></form>
}
export function ProjectEditor({initial}:{initial:ProjectRecord[]}){const [records,setRecords]=useState(initial),[selected,setSelected]=useState(0),[dirty,setDirty]=useState(false);useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);const canLeave=()=>!dirty||window.confirm('Quitter cette fiche sans enregistrer les modifications ?');return <div className="cms"><header><a href="/">Étape Zero</a><h1>Projets</h1><a href="/admin/services">Gérer les services</a><a href="/admin/articles">Gérer les articles</a><p>Une seule fiche pour la carte et l’étude de cas.</p></header><div className="cms-picker"><Choice label="Projet à modifier" value={String(selected)} options={records.map((r,i)=>[String(i),(r.project.title||'Nouveau projet')+(r.project.published?'':' · Brouillon')])} onChange={v=>{if(canLeave()){setSelected(Number(v));setDirty(false);}}}/><Button variant="outline" onClick={()=>{if(canLeave()){setRecords([...records,{project:blankProject(),revision:0}]);setSelected(records.length);setDirty(false);}}}>Nouveau projet</Button></div><Editor key={selected} initial={records[selected]} onDirty={setDirty} onSaved={record=>setRecords(list=>list.map((r,i)=>i===selected?record:r))}/></div>}
