import {ProjectVideo} from './ProjectVideo';
import {isVideoSource} from '@/lib/cms/media';
import {SiteHeader,SiteCTA,SiteFooter} from '@/components/home/Home';
import {ProjectCard,type Project} from '@/components/design-system/Component';
import type {CMSProject,Photo} from '@/lib/cms/project-schema';
export function ProjectPhoto({photo,hero=false}:{photo:Photo;hero?:boolean}){return <div className={'case-photo'+(hero?' case-hero':'')}>{photo.src?isVideoSource(photo.src)?<ProjectVideo src={photo.src} poster={photo.poster} alt={photo.alt} style={{objectFit:photo.fit,objectPosition:photo.position}}/>:<img src={photo.src} alt={photo.alt} loading={hero?'eager':'lazy'} style={{objectFit:photo.fit,objectPosition:photo.position}}/>:<div className="case-photo-pending"><span>Visuel à venir</span></div>}</div>}
function Gallery({photos}:{photos:Photo[]}){return photos.length?<div className={'case-gallery'+(photos.length===1?' single':'')}>{photos.map((photo,i)=><ProjectPhoto key={i} photo={photo}/>)}</div>:null;}
function Story({title,text}:{title:string;text:string}){return text?<section className="case-story"><h2>{title}</h2><p>{text}</p></section>:null;}
export function ProjectDetail({project:p,related}:{project:CMSProject;related:Project[]}){return <div className="home case-page"><a href="#contenu" className="home-skip">Aller au contenu</a><SiteHeader/><main id="contenu"><div className="case-layout home-gutter"><aside className="case-info"><div><h1>{p.title}</h1><dl>{[['Projet',p.category],['Secteur',p.sector],['Année',p.year],['Développement',p.development.join('\n')]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div>{p.services.length>0&&<ul className="case-services" aria-label="Services réalisés">{p.services.map((service,i)=><li key={i}>{service}</li>)}</ul>}</aside><ProjectPhoto photo={p.hero} hero/><div className="case-body"><Story title="Le contexte" text={p.context}/><Gallery photos={p.galleries.context}/><Story title="Les enjeux" text={p.challenges}/><Gallery photos={p.galleries.challenges}/><Story title="Nos décisions" text={p.decisions}/><Gallery photos={p.galleries.decisions}/>{(p.results||p.metrics.length>0)&&<section className="case-story case-results"><div><h2>Les résultats</h2>{p.metrics.length>0&&<dl className="case-metrics">{p.metrics.map((metric,i)=><div key={i}><dt>{metric.value}</dt><dd>{metric.label}</dd></div>)}</dl>}</div><p>{p.results}</p></section>}<Gallery photos={p.galleries.results}/></div></div>{related.length>0&&<section className="case-related home-gutter" aria-labelledby="related-title"><h2 id="related-title">Nos récentes études de cas</h2><div className="case-related-grid">{related.map(project=><ProjectCard key={project.id} project={project} format="narrow"/>)}</div></section>}<SiteCTA/></main><SiteFooter/></div>}
