import type {Metadata} from 'next';
import {SiteHeader,SiteFooter} from '@/components/home/Home';
import '../home.css';
import './legal.css';
export const metadata:Metadata={title:'Mentions légales — Étape Zero',description:'Informations légales et coordonnées du studio Étape Zero.'};
export default function Page(){return <div className="home legal-page"><a className="home-skip" href="#contenu">Aller au contenu</a><SiteHeader/><main id="contenu" className="legal-content"><header><h1>Mentions légales</h1><p>Dernière mise à jour : <time dateTime="2026-09-28">28 septembre 2026</time></p></header>
<section><h2>1 — Édition du site</h2><p>Le site <strong>etapezero.fr</strong> est édité par :</p><ul>
<li><strong>Dénomination :</strong> Étape Zero</li><li><strong>Nom commercial :</strong> Étape Zero</li><li><strong>Forme juridique :</strong> Entrepreneur individuel (EI)</li><li><strong>Adresse :</strong> 215 Route du Chanet, Saint-Pierre-de-Soucy, 73800, France</li><li><strong>SIREN :</strong> 947 661 278</li><li><strong>Numéro de TVA intracommunautaire :</strong> FR79947661278</li><li><strong>Téléphone :</strong> <a href="tel:+33676110719">06 76 11 07 19</a></li><li><strong>Email :</strong> <a href="mailto:contact@etapezero.com">contact@etapezero.com</a></li><li><strong>Directeur de la publication :</strong> Clément Le Baillif</li></ul></section>
<section><h2>2 — Hébergement</h2><p>Le site <strong>etapezero.fr</strong> est hébergé par :</p><p><strong>Vercel Inc.</strong><br/>440 N Barranca Avenue #4133<br/>Covina, CA 91723<br/>États-Unis</p><p>Le nom de domaine est enregistré auprès de <strong>IONOS</strong>.</p></section>
<section><h2>3 — Propriété intellectuelle</h2><p>L'ensemble des éléments présents sur le site etapezero.fr, notamment les textes, graphismes, éléments d'identité visuelle, logos, icônes, illustrations, vidéos, animations, designs, structure et éléments constituant le site, sont protégés par le droit français et international relatif à la propriété intellectuelle.</p><p>Sauf mention contraire, ces éléments sont la propriété d'Étape Zero ou sont utilisés avec l'autorisation de leurs titulaires respectifs.</p><p>Toute reproduction, représentation, modification, publication, adaptation ou exploitation, totale ou partielle, des éléments appartenant à Étape Zero, par quelque procédé et sur quelque support que ce soit, sans autorisation écrite préalable, est interdite et susceptible de constituer une contrefaçon au sens du Code de la propriété intellectuelle.</p><p>Le site présente également des réalisations, études de cas, marques, logos, photographies et autres éléments appartenant à des clients ou partenaires d'Étape Zero. Ces éléments restent la propriété de leurs titulaires respectifs et sont présentés dans le cadre de la présentation des prestations et réalisations d'Étape Zero.</p><p>Les marques tierces éventuellement mentionnées sur le site restent la propriété de leurs détenteurs respectifs.</p></section>
<section><h2>4 — Responsabilité</h2><p>Les informations publiées sur etapezero.fr sont fournies à titre informatif. Étape Zero s'efforce d'assurer l'exactitude et la mise à jour des informations diffusées sur le site, mais ne peut garantir l'absence d'erreurs, d'omissions ou d'informations devenues obsolètes.</p><p>Étape Zero ne pourra être tenu responsable des dommages directs ou indirects résultant de l'accès au site, de son utilisation, de l'impossibilité d'y accéder ou de l'utilisation des informations qui y sont présentées.</p><p>L'utilisateur est responsable de la protection de ses équipements, de sa connexion et de ses données lors de l'utilisation du site.</p><p>Le site a vocation à présenter l'activité, les prestations et les réalisations d'Étape Zero et à permettre aux visiteurs de prendre contact. Aucun achat ou paiement n'est réalisé directement sur le site.</p></section>
<section><h2>5 — Protection des données personnelles</h2><p>Dans le cadre de l'utilisation du site et notamment du formulaire de contact, Étape Zero peut collecter certaines données personnelles telles que :</p><ul><li>nom et prénom ;</li><li>adresse email ;</li><li>entreprise ;</li><li>sujet de la demande ;</li><li>budget ;</li><li>contenu du message ;</li><li>ainsi que toute information volontairement communiquée par l'utilisateur.</li></ul><p>Ces données sont utilisées afin de traiter les demandes reçues, répondre aux utilisateurs et assurer le suivi des échanges commerciaux.</p><p>Elles ne sont pas destinées à être vendues à des tiers.</p><p>Conformément au Règlement général sur la protection des données (RGPD) et à la loi Informatique et Libertés modifiée, chaque utilisateur dispose notamment d'un droit d'accès, de rectification, d'effacement, de limitation, d'opposition et, lorsque celui-ci est applicable, d'un droit à la portabilité de ses données personnelles.</p><p>Pour exercer ces droits ou pour toute question concernant le traitement des données personnelles, l'utilisateur peut contacter Étape Zero à l'adresse suivante :</p><p><a href="mailto:contact@etapezero.com"><strong>contact@etapezero.com</strong></a></p><p>Pour davantage d'informations concernant le traitement des données personnelles et l'utilisation des cookies, l'utilisateur peut consulter la Politique de confidentialité du site.</p></section>
<section><h2>6 — Cookies</h2><p>Le site etapezero.fr utilise des cookies et technologies similaires nécessaires à son fonctionnement ainsi que des outils de mesure d'audience, notamment <strong>Google Analytics</strong>.</p><p>Les cookies qui ne sont pas strictement nécessaires au fonctionnement du site ne sont déposés qu'après obtention du consentement de l'utilisateur, lorsque celui-ci est requis.</p><p>L'utilisateur peut accepter, refuser ou modifier ses préférences concernant les cookies via l'outil de gestion du consentement mis à sa disposition sur le site.</p><p>Il peut également configurer son navigateur afin de limiter ou supprimer certains cookies.</p></section>
<section><h2>7 — Liens externes</h2><p>Le site etapezero.fr peut contenir des liens renvoyant vers des sites ou services exploités par des tiers.</p><p>Étape Zero n'exerce aucun contrôle sur ces sites externes et ne saurait être tenu responsable de leur contenu, de leur disponibilité, de leurs pratiques ou de leur politique de confidentialité.</p></section>
<section><h2>8 — Droit applicable</h2><p>Les présentes mentions légales sont soumises au droit français.</p><p>En cas de différend, les parties sont invitées à rechercher en priorité une solution amiable. À défaut, le litige sera porté devant les juridictions compétentes conformément aux règles de droit applicables.</p></section>
</main><SiteFooter/></div>}
