'use client';
import {useState} from 'react';
import {ProjectVideo} from '@/components/projects/ProjectVideo';
import {SiteHeader,SiteCTA,SiteFooter} from '@/components/home/Home';
import {Button} from '@/components/ui/button';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {ServicePhoto,ServiceCard} from './ServiceCard';
import type {CMSService} from '@/lib/cms/service-schema';
import type {CMSProject} from '@/lib/cms/project-schema';
function Paragraphs({text}:{text:string}){return <>{text.split(/\n\s*\n/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</>}
export function ServiceDetail({service:s,project,related}:{service:CMSService;project?:CMSProject;related:CMSService[]}){const [reading,setReading]=useState(true);return <div className="home service-detail"><a className="home-skip" href="#contenu">Aller au contenu</a><SiteHeader/><main id="contenu"><section className="sd-hero"><p>{s.heroLabel}</p><h1>{s.title}</h1><div className="sd-intro"><Paragraphs text={s.intro||s.description}/></div><div className="sd-actions"><Button asChild><a href="/contact">Nous contacter</a></Button><Button asChild variant="secondary"><a href="mailto:contact@etapezero.com?subject=Demande%20de%20rendez-vous">Prendre rendez-vous</a></Button></div></section>
 {(s.videoTitle||s.videoUrl||s.transcriptLeft||s.transcriptRight)&&<section className="sd-video sd-container">{s.videoUrl?<ProjectVideo poster={s.videoPoster.src||undefined} src={s.videoUrl} alt={s.videoTitle}/>:<ServicePhoto photo={s.videoPoster} className="sd-video-poster"/>}<div className="sd-video-heading"><h2>{s.videoTitle}</h2><Button variant="secondary" aria-expanded={reading} aria-controls="service-transcript" onClick={()=>setReading(v=>!v)}>{reading?'Masquer le texte':'Vous préférez lire ?'}</Button></div>{reading&&<div id="service-transcript" className="sd-transcript"><div><Paragraphs text={s.transcriptLeft}/></div><div><Paragraphs text={s.transcriptRight}/></div></div>}</section>}
 {s.studioTitle&&<section className="sd-studio sd-container"><div className="sd-collage">{s.studioPhotos.map((photo,i)=><ServicePhoto key={i} photo={photo}/>)}</div><div><h2>{s.studioTitle}</h2><Paragraphs text={s.studioText}/></div></section>}
 {project?.published&&<section className="sd-case sd-container"><h2>Étude de cas</h2><div><ServicePhoto photo={project.cover.src?project.cover:project.hero}/><div className="sd-case-copy"><div><h3>{project.title}</h3><p>{s.projectDescription||project.description}</p></div><dl>{project.metrics.map((m,i)=><div key={i}><dt>{m.value}</dt><dd>{m.label}</dd></div>)}</dl><Button asChild variant="secondary"><a href={'/projets/'+project.id}>Voir l’étude de cas</a></Button></div></div></section>}
 {s.benefitTitle&&<section className="sd-benefits sd-container"><h2>{s.benefitTitle}</h2><Paragraphs text={s.benefitText}/><ServicePhoto photo={s.benefitPhoto}/></section>}
 {!!s.features.length&&<section className="sd-features home-gutter"><h2>L’accompagnement comprend</h2><div>{s.features.map((f,i)=><article key={i}><ServicePhoto photo={f.photo}/><h3>{f.title}</h3><p className="sd-tags">{f.tags}</p><p>{f.text}</p></article>)}</div></section>}
 {(s.outcomes.length>0||s.deliverables.length>0)&&<section className="sd-delivery sd-container"><ServicePhoto photo={s.deliveryPhoto}/><div>{[['Ce que vous construisez',s.outcomes],['Ce que nous vous livrons',s.deliverables]].map(([title,items],i)=><div key={i}><h2>{title as string}</h2><ul className={i===0?'sd-chips':''}>{(items as string[]).map((item,j)=><li key={j}>{item}</li>)}</ul></div>)}</div></section>}
 {!!s.faq.length&&<section className="sd-faq home-gutter"><h2>Les questions que vous vous posez avant de commencer</h2><div><ServicePhoto photo={s.faqPhoto}/><div><Accordion type="single" collapsible>{s.faq.map((f,i)=><AccordionItem key={i} value={String(i)}><AccordionTrigger><span className="hover-underline">{f.question}</span></AccordionTrigger><AccordionContent><Paragraphs text={f.answer}/></AccordionContent></AccordionItem>)}</Accordion><Button asChild><a href="/contact">Nous contacter</a></Button></div></div></section>}
 {!!related.length&&<section className="sd-related home-gutter"><h2>Nos autres expertises</h2>{related.map(service=><ServiceCard key={service.id} service={service}/>)}</section>}<SiteCTA/></main><SiteFooter/></div>}
