'use client';
import {useEffect,useRef,useState} from 'react';
import {SiteHeader,SiteCTA,SiteFooter} from '@/components/home/Home';
import {Button} from '@/components/ui/button';
import {articleDate,readingTime,type CMSArticle} from '@/lib/cms/article-schema';
import {ProjectVideo} from '@/components/projects/ProjectVideo';
import {isVideoSource} from '@/lib/cms/media';
import type {Photo} from '@/lib/cms/project-schema';
export function ArticlePhoto({photo,className=''}:{photo:Photo;className?:string}){return <div className={'article-photo '+className}>{photo.src?isVideoSource(photo.src)?<ProjectVideo src={photo.src} poster={photo.poster} alt={photo.alt} style={{objectFit:photo.fit,objectPosition:photo.position}}/>:<img src={photo.src} alt={photo.alt} style={{objectFit:photo.fit,objectPosition:photo.position}}/>:<span>Visuel à venir</span>}</div>}
export function ArticleHub({articles}:{articles:CMSArticle[]}){const [filter,setFilter]=useState('Tous les articles'),[limit,setLimit]=useState(8);const categories=[...new Set(['Positionnement','Rebranding','Valeur perçue','Système graphique','Business',...articles.map(a=>a.category)])];const matches=articles.filter(a=>filter==='Tous les articles'||a.category===filter);return <div className="home journal"><SiteHeader/><main><section className="journal-hero"><h1>Le Journal</h1><p>Du positionnement à l’expérience digitale, découvrez les principes, les méthodes et les réflexions qui guident notre manière de concevoir les marques.</p></section><section className="journal-list home-gutter" aria-label="Articles"><div className="journal-filters">{['Tous les articles',...categories].map(c=><Button key={c} variant="secondary" aria-pressed={filter===c} onClick={()=>{setFilter(c);setLimit(8)}}>{c}</Button>)}</div><div className="journal-grid">{matches.slice(0,limit).map(a=><a className="article-card" key={a.id} href={'/journal/'+a.id}><ArticlePhoto photo={a.cover.src?a.cover:a.hero} className={a.cardFormat}/><div className="article-card-meta"><span>{a.category}</span><time dateTime={a.date}>{articleDate(a.date)}</time></div><h2>{a.title}</h2><p>{a.excerpt}</p><small>{readingTime(a)} min de lecture</small></a>)}</div>{!matches.length&&<p className="journal-empty" role="status">Aucun article dans cette catégorie pour le moment.</p>}{matches.length>limit&&<Button className="journal-more" variant="link" onClick={()=>setLimit(n=>n+8)}>Charger plus d’articles</Button>}</section><SiteCTA/></main><SiteFooter/></div>}
export function ArticleDetail({article:a}:{article:CMSArticle}){const ref=useRef<HTMLDivElement>(null);const [progress,setProgress]=useState(0);useEffect(()=>{let frame=0;const measure=()=>{frame=0;if(!ref.current)return;const box=ref.current.getBoundingClientRect();setProgress(Math.max(0,Math.min(1,(100-box.top)/Math.max(1,box.height-window.innerHeight+100))));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(measure)};measure();window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule)}},[]);return <div className="home journal"><SiteHeader/><main><article className="article-detail"><div className="article-reading" ref={ref}><div className="article-progress-track"><aside className="article-progress" aria-label="Progression de lecture"><span>{Math.floor(readingTime(a)*progress)} min</span><div role="progressbar" aria-label="Lecture" aria-valuenow={Math.round(progress*100)} aria-valuemin={0} aria-valuemax={100}><i style={{height:progress*100+'%'}}/></div><span>{readingTime(a)} min</span></aside></div><div className="article-column"><header className="article-intro"><h1>{a.title}</h1><p>{a.intro}</p></header><div><div className="article-meta"><time dateTime={a.date}>{articleDate(a.date)}</time><a href={'/journal'}>{a.category}</a></div><ArticlePhoto photo={a.hero.src?a.hero:a.cover} className="article-hero-image"/></div><nav className="article-toc" aria-label="Sommaire"><ol>{a.sections.map((s,i)=>s.title&&<li key={i}><a href={'#section-'+i}>{s.title}</a></li>)}</ol></nav><div className="article-body">{a.sections.map((s,i)=><section key={i} id={'section-'+i}>{s.title&&<h2>{s.title}</h2>}{s.subtitle&&<h3>{s.subtitle}</h3>}{s.text.split(/\n\s*\n/).filter(Boolean).map((p,j)=><p key={j}>{p}</p>)}{!!s.bullets.length&&<ul>{s.bullets.map((b,j)=><li key={j}>{b}</li>)}</ul>}{s.quote&&<blockquote>{s.quote}</blockquote>}{!!s.photos.length&&<div className={'article-gallery '+(s.photos.length===1?'single':'')}>{s.photos.map((photo,j)=><ArticlePhoto photo={photo} key={j}/>)}</div>}</section>)}</div>{a.closing&&<p className="article-closing">{a.closing}</p>}</div></div><div className="article-author"><ArticlePhoto photo={a.authorPhoto}/><div><p>{a.author}</p><p>{a.authorRole}</p></div></div></article><SiteCTA/></main><SiteFooter/></div>}
