'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {PhotoField} from '@/components/projects/ProjectEditor';
import {blankPhoto} from '@/lib/cms/project-schema';
import {blankArticle,blankSection,readingTime,type CMSArticle,type ArticleRecord} from '@/lib/cms/article-schema';
function Editor({initial,onSaved,onDirty}:{initial:ArticleRecord;onSaved:(r:ArticleRecord)=>void;onDirty:(v:boolean)=>void}){const [a,setArticle]=useState(initial.article),[revision,setRevision]=useState(initial.revision),[busy,setBusy]=useState(false),[uploads,setUploads]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('');const update=(next:CMSArticle)=>{setArticle(next);onDirty(true);setMessage('')};const field=(key:keyof CMSArticle,value:unknown)=>update({...a,[key]:value});const section=(i:number,key:string,value:unknown)=>field('sections',a.sections.map((s,j)=>j===i?{...s,[key]:value}:s));const upload=(delta:number)=>{setUploads(n=>n+delta);if(delta>0)onDirty(true)};
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/admin/articles',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({article:a,revision})});const data=await response.json() as {error?:string;revision:number};if(!response.ok)throw new Error(data.error);setRevision(data.revision);onSaved({article:a,revision:data.revision});onDirty(false);setMessage(a.published?'Article enregistré et publié.':'Brouillon enregistré.');}catch(e){setError(e instanceof Error?e.message:'La sauvegarde a échoué.')}finally{setBusy(false)}}
 return <form onSubmit={save}><div className="cms-toolbar"><h2>{a.title||'Nouvel article'}</h2><Button disabled={busy||uploads>0}>Enregistrer</Button></div><p role="status">{message|| (uploads?'Import en cours…':'')}</p>{error&&<p role="alert" className="cms-error">{error}</p>}<fieldset className="cms-fields" disabled={busy||uploads>0}><section><h3>Informations de l’article</h3><div className="cms-grid">{([['title','Titre'],['id','Identifiant dans l’URL'],['category','Catégorie'],['date','Date de publication'],['author','Auteur'],['authorRole','Fonction de l’auteur']] as const).map(([key,label])=><label className="cms-field" key={key}><span>{label}</span><Input required={['title','id','category','date'].includes(key)} type={key==='date'?'date':'text'} readOnly={key==='id'&&(!!initial.article.id||revision>0)} pattern={key==='id'?'[a-z0-9]+(-[a-z0-9]+)*':undefined} value={a[key]} onChange={e=>field(key,e.target.value)}/></label>)}<label className="cms-field"><span>Temps de lecture en minutes — 0 pour automatique ({readingTime({...a,readingMinutes:0})} min)</span><Input type="number" min={0} max={999} value={a.readingMinutes} onChange={e=>field('readingMinutes',Number(e.target.value))}/></label><label className="cms-field"><span>Format de la carte</span><Select value={a.cardFormat} onValueChange={v=>field('cardFormat',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="landscape">Paysage</SelectItem><SelectItem value="portrait">Portrait</SelectItem></SelectContent></Select></label></div>{([['excerpt','Résumé sur le hub'],['intro','Introduction'],['closing','Mot de fin']] as const).map(([key,label])=><label className="cms-field" key={key}><span>{label}</span><Textarea rows={4} value={a[key]} onChange={e=>field(key,e.target.value)}/></label>)}<div className="cms-options"><label><Checkbox checked={a.published} onCheckedChange={v=>field('published',v===true)}/>Publier l’article</label><label><Checkbox checked={a.listed} onCheckedChange={v=>field('listed',v===true)}/>Afficher sur le hub</label></div><p>Les brouillons restent invisibles sur le site. La couverture, le titre, le résumé, la catégorie, la date et le temps de lecture alimentent automatiquement la carte.</p></section><section><h3>Photos principales</h3><div className="cms-grid">{([['cover','Couverture du hub'],['hero','Photo d’ouverture'],['authorPhoto','Photo de l’auteur']] as const).map(([key,label])=><PhotoField key={key} label={label} photo={a[key]} onChange={v=>field(key,v)} onUpload={upload}/>)}</div></section>
 <section><h3>Contenu et sommaire</h3><p>Chaque section titrée est ajoutée au sommaire. Séparez les paragraphes par une ligne vide.</p>{a.sections.map((s,i)=><section key={i}><h4>Section {i+1}</h4>{([['title','Titre de section'],['subtitle','Sous-titre'],['text','Texte'],['quote','Citation']] as const).map(([key,label])=><label className="cms-field" key={key}><span>{label}</span>{key==='text'?<Textarea rows={8} value={s[key]} onChange={e=>section(i,key,e.target.value)}/>:<Input value={s[key]} onChange={e=>section(i,key,e.target.value)}/>}</label>)}<label className="cms-field"><span>Liste à puces — une par ligne</span><Textarea value={s.bullets.join('\n')} onChange={e=>section(i,'bullets',e.target.value.split('\n'))}/></label><div className="cms-grid">{s.photos.map((p,j)=><div key={j}><PhotoField label={'Photo '+(j+1)} photo={p} onChange={v=>section(i,'photos',s.photos.map((x,k)=>k===j?v:x))} onUpload={upload}/><Button type="button" variant="outline" disabled={j===0} onClick={()=>{const next=[...s.photos];[next[j-1],next[j]]=[next[j],next[j-1]];section(i,'photos',next)}}>Monter la photo</Button><Button type="button" variant="outline" onClick={()=>section(i,'photos',s.photos.filter((_,k)=>k!==j))}>Retirer</Button></div>)}</div><div className="cms-photo-actions"><Button type="button" variant="outline" disabled={s.photos.length>=12} onClick={()=>section(i,'photos',[...s.photos,blankPhoto()])}>Ajouter une photo</Button><Button type="button" variant="outline" disabled={i===0} onClick={()=>{const next=[...a.sections];[next[i-1],next[i]]=[next[i],next[i-1]];field('sections',next)}}>Monter la section</Button><Button type="button" variant="outline" disabled={i===a.sections.length-1} onClick={()=>{const next=[...a.sections];[next[i],next[i+1]]=[next[i+1],next[i]];field('sections',next)}}>Descendre la section</Button><Button type="button" variant="outline" onClick={()=>{if(window.confirm('Retirer cette section ?'))field('sections',a.sections.filter((_,j)=>j!==i))}}>Retirer la section</Button></div></section>)}<Button type="button" variant="outline" disabled={a.sections.length>=60} onClick={()=>field('sections',[...a.sections,blankSection()])}>Ajouter une section</Button></section></fieldset><div className="cms-toolbar"><Button disabled={busy||uploads>0}>Enregistrer</Button>{a.id&&(initial.article.id||revision>0)&&<a href={'/admin/articles/apercu?id='+a.id} target="_blank" rel="noreferrer">Voir la version enregistrée ↗</a>}</div></form>;
}
export function ArticleEditor({initial}:{initial:ArticleRecord[]}){const [records,setRecords]=useState(initial.length?initial:[{article:blankArticle(),revision:0}]),[selected,setSelected]=useState(0),[dirty,setDirty]=useState(false);useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);const canLeave=()=>!dirty||window.confirm('Quitter sans enregistrer les modifications ?');return <div className="cms"><header><a href="/journal">← Le Journal</a><h1>Articles</h1><a href="/admin/services">Gérer les services</a><p>Une seule fiche pour l’article et sa carte.</p><a href="/admin/projets">Gérer les projets</a></header><div className="cms-picker"><Select value={String(selected)} onValueChange={v=>{if(canLeave()){setSelected(Number(v));setDirty(false)}}}><SelectTrigger aria-label="Article à modifier"><SelectValue/></SelectTrigger><SelectContent>{records.map((r,i)=><SelectItem key={i} value={String(i)}>{r.article.title||'Nouvel article'}{!r.article.published?' · Brouillon':''}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>{if(canLeave()){setRecords([...records,{article:blankArticle(),revision:0}]);setSelected(records.length);setDirty(false)}}}>Nouvel article</Button></div><Editor key={selected} initial={records[selected]} onDirty={setDirty} onSaved={record=>setRecords(list=>list.map((r,i)=>i===selected?record:r))}/></div>}
